### ISSUE TITLE
Classnames to add

### ISSUE THREAD

**Issue by micahwhitsel** [7Cav/7CavAddon#102]
Charlie Weapons Loadouts

- [x] Cav_B_C_MMGTeamLead_F
- [x] Cav_B_C_MMGGunner_F
- [x] Cav_B_C_MMGAssistant_F
- [x] Cav_B_C_SLMTeamLead_F
- [x] Cav_B_C_SLMGunner_F
- [x] Cav_B_C_SLMAmmoBearer_F

Bravo Cav Scouts

- [x] Cav_B_B_Driver_F
- [x] Cav_B_B_Gunner_F
- [x] Cav_B_B_Scout_PlatoonLeader_F
- [x] Cav_B_B_Scout_PlatoonSergeant_F
- [x] Cav_B_B_Scout_SquadLead_F
- [x] Cav_B_B_Scout_AutomaticRifleman_F
- [x] Cav_B_B_Scout_Grenadier_F
- [x] Cav_B_B_Scout_CombatLifeSaver_F

Name Changes
- [x] Cav_B_B_Scout_Driver_F name changed from Driver to Scout Driver
- [x] Cav_B_B_Scout_Gunner_F name changed from Gunner to Scout Gunner

**Comment by micahwhitsel** [comment]
Old havoc callsigns are being repurposed for Charlie weapons quads

**Comment by ColdEvul** [comment]
better to make new ones don't you think?

**Comment by micahwhitsel** [comment]
> better to make new ones don't you think?

Is this for the weapons squads?

**Comment by ColdEvul** [comment]
like new classnames for weapon units.
or I might be confuced ^^

**Comment by micahwhitsel** [comment]
> like new classnames for weapon units.
> or I might be confuced ^^

Ok, that's fine with me. I'll use them if you add them. Updating the issue with the weapon squad classes.

**Comment by Robot-Panda15** [comment]
@micahwhitsel see #109

**Comment by micahwhitsel** [comment]
Thanks @Robot-Panda15 
I have no idea how to do these, so would you be able to handle charlie weapon classnames as well?

**Comment by Robot-Panda15** [comment]
Adding additional "Cav_B_C_WSL_F" for Weapons Squad Leader
see #118 @micahwhitsel
