### ISSUE TITLE
Change Apollo Team Members to have similar fire team roles

### ISSUE THREAD

**Issue by Robot-Panda15** [7Cav/7CavAddon#17]
Apollo Team Composition:
Apollo Team Leader (Apollo-1)
Apollo Grenadier
Apollo Machine Gunner
Apollo Team Leader
Apollo Grenadier
Apollo Machine Gunner

-It's still one team, but they can separate as needed into two smaller teams.

**Comment by ColdEvul** [comment]
Team structure and loadouts required

**Comment by Robot-Panda15** [comment]
seen, will get them in when I can.

**Comment by Robot-Panda15** [comment]
These will utilize the same Apollo Logistics Loadouts that were recently updated before CavAddon.
