### ISSUE TITLE
Remove unused class inherit

### ISSUE THREAD

**Issue by AndreasBrostrom** [7Cav/7CavAddon#203]
This inherit is not used

https://github.com/7Cav/7CavAddon/blob/14c86cf9777a98b7611a0f57ab42a41b0f064ead/addons/vehicles_dragoon/CfgVehicles.hpp#L2

**Comment by pool011** [comment]
> This inherit is not used
> 
> https://github.com/7Cav/7CavAddon/blob/14c86cf9777a98b7611a0f57ab42a41b0f064ead/addons/vehicles_dragoon/CfgVehicles.hpp#L2

I am creating a PR, but was this tested?

**Comment by AndreasBrostrom** [comment]
it's not references so It should be fine
