### ISSUE TITLE
Add Joint Fires Observer in Bravo Troop Infantry

### ISSUE THREAD

**Issue by Robot-Panda15** [7Cav/7CavAddon#21]
Add in Bravo Troop Infantry category:
Joint Fires Observer
Joint Fires Observer (Infidel-1)
Joint Fires Observer (Loki-1)

**Comment by ColdEvul** [comment]
All special and officers are in Alpha for convenience

**Comment by ColdEvul** [comment]
- [ ] Joint Fires Observer
- [ ] Joint Fires Observer (Infidel-1)
- [ ] Joint Fires Observer (Loki-1)

**Comment by ColdEvul** [comment]
loki is missing
