### ISSUE TITLE
Add Cavalry Scout Classes 

### ISSUE THREAD

**Issue by Robot-Panda15** [7Cav/7CavAddon#35]
Add Cavalry Scout units to Bravo Troop

**Comment by Robot-Panda15** [comment]
Please mark as WIP, will be working in tandem with Cav Scout Loadouts on cScripts once I have details

**Comment by Robot-Panda15** [comment]
Will update at later date with unit names that we can work on for the string table

**Comment by Robot-Panda15** [comment]
Cav Scout Classes to be added:
Cavalry Scout Driver
Cavalry Scout Gunner
Cavalry Scout Vehicle Commander
Cavalry Scout Platoon Leader
Cavalry Scout Platoon Sergeant
Cavalry Scout Dismount

**Comment by ColdEvul** [comment]
Base class: `Cav_B_Bravo_Scout_base_F`

**Comment by Robot-Panda15** [comment]
> Base class: `Cav_B_Bravo_Scout_base_F`

`Cav_B_Bravo_Scout_Driver_F
Cav_B_Bravo_Scout_Gunner_F
Cav_B_Bravo_Scout_VC_F
Cav_B_Bravo_Scout_PL_F
Cav_B_Bravo_Scout_PSG_F
Cav_B_Bravo_Scout_Infantry_F`

**Comment by ColdEvul** [comment]
classes look green
you think you can do it in the mod as well?

**Comment by Robot-Panda15** [comment]
Not sure where to find them

**Comment by ColdEvul** [comment]
just copy a rifleman and basicly do the same as you done for them here and add them here: https://github.com/7Cav/7CavAddon/blob/master/addons/bravo_characters/CfgVehicles.hpp#L639
