### ISSUE TITLE
Cav UH-60 Variants missing Passenger Left/Right 1 and 2 Options

### ISSUE THREAD

**Issue by Robot-Panda15** [7Cav/7CavAddon#56]
UH-60 variant is missing 4 slots. The Passenger Left Bench 1, Passenger Left Bench 2, Passenger Right Bench 1, and Passenger Right Bench 2. These are the positions that are the outward-most seats that allow you to shoot your gun from the side of the helicopter. Without these, we are limited to only 8 seats per bird, making them ineffective for use.

**Comment by ColdEvul** [comment]
That is odd I will dig and se why this might happen.

**Comment by Robot-Panda15** [comment]
There are only "Ride in Back" options, which is only 8 positions in the RHS UH-60. The other 4 are the "Passenger Right/Left 1/2"

**Comment by ColdEvul** [comment]
in theory it should work the same as the rhs one cause it inherit everything but aperently something is messed up.

**Comment by ColdEvul** [comment]
Will I fixed it kind of tho the unarmed variant got 2-4 extra spots...
Back to the work table...
