### ISSUE TITLE
Current 7Cav UH-60M under Alpha Vehicles

### ISSUE THREAD

**Issue by zeppelinmetal** [7Cav/7CavAddon#64]
7Cav UH-60M has doors. These cause a sound bug from time to time that distracts the pilots. Lindsey is requesting the UH-60M without doors (this version can be found under the USArmy-D).

**Comment by ColdEvul** [comment]
Still the case?

**Comment by ColdEvul** [comment]
closed due to being stale. 
Reopen if the issue is still precent.
