### ISSUE TITLE
Complete Company Compositions/Template

### ISSUE THREAD

**Issue by RaynorD** [7Cav/7CavAddon#66]
While rebuilding the units on the A Co training maps, I had to spend a great deal of time filling in init and description fields manually, since CfgGroups doesn't support them and the compositions didn't have all units. It would be great if we had a master composition for each company that held all the slots we could ever need for that company. Here's the composition from my Alpha Co template.
[All_Units_Alpha_Company.zip](https://github.com/7Cav/7CavAddon/files/3571856/All_Units_Alpha_Company.zip)

If compositions don't meet our requirements, a template mission with all of our units certainly would. Mission makers could just copy the units they want and paste them into their mission.

**Comment by ColdEvul** [comment]
This is something I whant.

cScripts have compositions that is release along side of the script. I whould love to have company wide deployments in there as well.

https://github.com/7Cav/cScripts/tree/master/Compositions
https://github.com/7Cav/cScripts/wiki/Composition-Development

**Comment by RaynorD** [comment]
Yeah I really should have put this in cScripts. I'll work on this over there once I get some time.
