### ISSUE TITLE
Dynamic Objectives - A/1-7

### ISSUE THREAD

**Issue by RaynorD** [7Cav/7CavAddon#68]
- [x] Static CAS Range
- [x] Conditions
- [x] Marked LZ(s)
    - [ ] Enemy Presence
- [ ] Static Courses
    - [ ] [High Speed - High Stress LZ Course ](https://7cav.us/threads/high-speed-high-stress-lz-course.43803/#post-340868)
- [ ] Moving Convoy - Hold for Zen module

**Comment by ColdEvul** [comment]
Moving Convoy is this ai you refere to?
If so hold of on that cause Zen have a moduel for this that is reliable. 

https://github.com/zen-mod/ZEN/blob/master/addons/modules/functions/fnc_moduleConvoyParameters.sqf

No point doing unessesary work :D
