### ISSUE TITLE
Dynamic Objectives - Common

### ISSUE THREAD

**Issue by RaynorD** [7Cav/7CavAddon#80]
Structure:
- [ ] Expandable scroll wheel menu from bootcamp

Common Functions:
- [ ] DisableAI Toggle ("Pause" Mission to analyze tactical situation)
- All AI regardless of side
- Alert/play sound
- [ ] Heal all blufor
- [ ] Toggle blufor invincibility

**Comment by ColdEvul** [comment]
this exist in cScripts half and half atleast as a WIP
